### ISSUE TITLE
Switching babel to babel-cli

### ISSUE THREAD

**Issue by jan-tosovsky-cz** [mazko/jssnowball#5]
When running command `make esjava` I am getting the following warning:
```
$ make esjava
sed 's/\\u/\\\\u/g' js_snowball/lib/snowball.es6 |              \
babel                                                                   \
--compact=false                                                         \
--presets es2015                                                        \
--plugins transform-es2015-modules-umd --module-id snowballFactory |   \
sed 's/\\\\u/\\u/g' > js_snowball/lib/snowball.babel.js
You have mistakenly installed the `babel` package, which is a no-op in Babel 6.
Babel's CLI commands have been moved from the `babel` package to the `babel-cli` package.

    npm uninstall babel
    npm install --save-dev babel-cli

See http://babeljs.io/docs/usage/cli/ for setup instructions.
```

I managed to get es5 output using following steps:
`$ npm install -save-dev babel-cli`
`$ npx babel --compact=false --presets es2015 --plugins transform-es2015-modules-umd --module-id snowballFactory js_snowball/lib/snowball.es6 --out-file js_snowball/lib/snowball.babel.js`

Btw, comparing your and mine `snowball.babel.js` there is missing the first line in my output:
```
var _typeof = typeof Symbol === "function" && typeof Symbol.iterator === "symbol" ? function (obj) { return typeof obj; } : function (obj) { return obj && typeof Symbol === "function" && obj.constructor === Symbol ? "symbol" : typeof obj; };
```

This function is used in `_possibleConstructorReturn` and `_inherits functions` while in my output simple typeof is used instead there.

**Comment by mazko** [comment]
This worked for me:

```
nodeenv ~/virtualenvs/snowball --prebuilt
. ~/virtualenvs/snowball/bin/activate

npm i babel-preset-es2015 babel-plugin-transform-es2015-modules-umd babel-cli
npm i -g babel-cli

wget https://github.com/mazko/jssnowball/raw/master/js_snowball/lib/snowball.es6

sed 's/\\u/\\\\u/g' snowball.es6 |    \
babel                                                 \
--compact=false                                       \
--presets es2015                                      \
--plugins transform-es2015-modules-umd --module-id snowballFactory |   \
sed 's/\\\\u/\\u/g' > snowball.babel.js

echo '
var snowballFactory = require("./snowball.babel.js");
var rus = snowballFactory.newStemmer("russian");
console.log(rus.stem("чаво")); ' | node
```

**Comment by jan-tosovsky-cz** [comment]
To clarify my point - it would be nice to update your GNUmakefile script to ensure that babel works without further tweaking.
Btw, in my case I used `npx` as it is used on babel's usage page https://babeljs.io/docs/usage/cli/ - I am rather new to Node.js world so I am accepting any approach which works :-)

**Comment by jan-tosovsky-cz** [comment]
All this turned out as my fault, a newbie issue when not distinguishing the `-g` `npm` option correctly:
```
npm i -g babel-cli
npm i babel-preset-es2015 babel-plugin-transform-es2015-modules-umd babel-cli
```
When `-g` was missing when installing `babel-cli`, the GNUmakefile script failed to execute the corresponding `babel` command.

With that parameter in place it works even without that slightly cryptic intro:
```
nodeenv ~/virtualenvs/snowball --prebuilt
. ~/virtualenvs/snowball/bin/activate
```
