### ISSUE TITLE
Modifying javascript output to get it working

### ISSUE THREAD

**Issue by jan-tosovsky-cz** [mazko/jssnowball#6]
Comparing original ES6 output (https://github.com/mazko/jssnowball/raw/master/js_snowball/lib/snowball.es6) with mine generated via GNUmakefile I can see crucial differences in `eq_s` and `eq_s_b` methods, see `s.length` vs. `s.length()` in the following example:

original:
```javascript
key: 'eq_s$esjava$1',
value: function eq_s$esjava$1(s) {
    if (this.limit - this.cursor < s.length) return false;
    var i = void 0;
    for (i = 0; i !== s.length; i++) {
        if (this.current.charAt(this.cursor + i) !== s.charCodeAt(i)) return false;
    }
    this.cursor += s.length;
    return true;
}
```
mine:
```javascript
key: 'eq_s$esjava$1',
value: function eq_s$esjava$1(s) {
    if (this.limit - this.cursor < s.length()) return false;
    var i = void 0;
    for (i = 0; i !== s.length(); i++) {
        if (this.current.charAt(this.cursor + i) !== s.charAt(i)) return false;
    }
    this.cursor += s.length();
    return true;
}
```

That mine (babelized) returns a `TypeError: s.length is not a function`. 

It gets fixed when using `s.length` instead. Am I supposed to modify final es6/es5 code? It is not mentioned in Readme.md file. Or is it ESJava regression?

**Comment by mazko** [comment]
See updated readme https://github.com/mazko/jssnowball#easy
