### ISSUE TITLE
Hebrew stemmer

### ISSUE THREAD

**Issue by pantchox** [mazko/jssnowball#8]
Hi,

snowball looks very promising.
Is there any chance of creating hebrew stemmer, it should be similar to the arabic one.

Thanks!

**Comment by mazko** [comment]
Shalom )
I think official snowball https://github.com/snowballstem/snowball/tree/master/algorithms is better place to find answer about how steemers work an how to write custom one.

**Comment by pantchox** [comment]
Thanks!
